# Generated by Django 6.0.6 on 2026-07-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilutilisateur_cree_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='poste',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN_ORGANISATION', 'Admin organisation'), ('RESPONSABLE_DEPARTEMENT', 'Responsable département'), ('RESPONSABLE', 'Responsable'), ('AGENT', 'Agent')], default='AGENT', max_length=30),
        ),
        migrations.AddField(
            model_name='departement',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='accounts.organisation'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='accounts.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('organisation', 'nom')},
        ),
    ]
