# Generated by Django 6.0.6 on 2026-06-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureManuscrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_signature', models.ImageField(upload_to='signatures/manuscrites/')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('largeur', models.FloatField(default=150)),
                ('hauteur', models.FloatField(default=80)),
                ('date_apposition', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_manuscrite', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField()),
                ('cle_publique', models.TextField()),
                ('algorithme', models.CharField(default='ECDSA', max_length=50)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_numerique', to='documents.document')),
            ],
        ),
    ]
