# Generated by Django 6.0.6 on 2026-06-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_verification_hash_recalcule_historiqueoperation'),
        ('signatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaturenumerique',
            name='document',
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_signature', models.ImageField(blank=True, null=True, upload_to='signatures/manuscrites/')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('largeur', models.FloatField(default=150)),
                ('hauteur', models.FloatField(default=80)),
                ('signature_numerique', models.TextField()),
                ('cle_publique', models.TextField()),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SIGNE', 'Signé'), ('INVALIDE', 'Invalide')], default='SIGNE', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SignatureManuscrite',
        ),
        migrations.DeleteModel(
            name='SignatureNumerique',
        ),
    ]
