# Generated by Django 6.0.6 on 2026-06-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_remove_signaturenumerique_document_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='cle_publique',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature_numerique',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SIGNE', 'Signé'), ('INVALIDE', 'Invalide')], default='EN_ATTENTE', max_length=20),
        ),
    ]
