# Generated by Django 6.0.6 on 2026-07-08 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_statut_and_more'),
        ('signatures', '0003_alter_signature_cle_publique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['ordre', 'date_signature']},
        ),
        migrations.AddField(
            model_name='signature',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together={('document', 'utilisateur')},
        ),
    ]
