# Generated by Django 6.0.6 on 2026-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_alter_signature_options_signature_ordre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='page_numero',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
