# Generated by Django 6.0.6 on 2026-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0005_signature_page_numero_alter_signature_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SIGNE', 'SignÃ©'), ('INVALIDE', 'Invalide')], default='EN_ATTENTE', max_length=20),
        ),
    ]
