# Generated by Django 6.0.6 on 2026-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0006_alter_signature_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='source_signature',
            field=models.CharField(blank=True, choices=[('DRAW', 'Signature dessinée'), ('UPLOAD', 'Signature importée')], max_length=20),
        ),
    ]
