# Generated by Django 6.0.6 on 2026-06-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_document', models.CharField(max_length=64)),
                ('signataire_pseudonyme', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(blank=True, max_length=255)),
                ('adresse_contrat', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('ENREGISTRE', 'Enregistré'), ('ECHEC', 'Échec')], default='ENREGISTRE', max_length=20)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_blockchain', to='documents.document')),
            ],
        ),
    ]
