# Generated by Django 6.0.6 on 2026-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditblockchain',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditblockchain',
            name='timestamp_blockchain',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
