# Generated by Django 6.0.6 on 2026-06-20 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier_original', models.FileField(upload_to='documents/originaux/')),
                ('fichier_signe', models.FileField(blank=True, null=True, upload_to='documents/signes/')),
                ('hash_original', models.CharField(blank=True, max_length=64)),
                ('hash_signe', models.CharField(blank=True, max_length=64)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SIGNE', 'Signé'), ('VERIFIE', 'Vérifié'), ('INVALIDE', 'Invalide')], default='BROUILLON', max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaquetPreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_preuve', models.FileField(upload_to='preuves/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paquet_preuve', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_verifie', models.CharField(max_length=64)),
                ('resultat', models.CharField(choices=[('VALIDE', 'Valide'), ('INVALIDE', 'Invalide'), ('ERREUR', 'Erreur')], max_length=20)),
                ('message', models.TextField()),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='documents.document')),
            ],
        ),
    ]
