# Generated by Django 6.0.6 on 2026-06-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='hash_recalcule',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='HistoriqueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Téléversement'), ('SIGNATURE', 'Signature'), ('VERIFICATION', 'Vérification'), ('BLOCKCHAIN_RECORD', 'Enregistrement blockchain'), ('AI_ANALYSIS', 'Analyse IA'), ('PROOF_GENERATION', 'Génération paquet de preuve'), ('DOWNLOAD_PROOF', 'Téléchargement paquet de preuve')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='documents.document')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
