# Generated by Django 6.0.6 on 2026-06-25 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilutilisateur'),
        ('documents', '0002_verification_hash_recalcule_historiqueoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('SIGNE', 'Signé'), ('VERIFIE', 'Vérifié'), ('INVALIDE', 'Invalide')], default='BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Téléversement'), ('ACCESS_ASSIGNMENT', 'Attribution des accès'), ('SIGNATURE', 'Signature'), ('VERIFICATION', 'Vérification'), ('BLOCKCHAIN_RECORD', 'Enregistrement blockchain'), ('AI_ANALYSIS', 'Analyse IA'), ('PROOF_GENERATION', 'Génération paquet de preuve'), ('DOWNLOAD_SIGNED', 'Téléchargement document signé'), ('DOWNLOAD_PROOF', 'Téléchargement paquet de preuve')], max_length=40),
        ),
        migrations.CreateModel(
            name='AccesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_signer', models.BooleanField(default=True)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_autorises', to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_autorises', to='accounts.departement')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='documents.document')),
            ],
            options={
                'verbose_name': 'Accès document',
                'verbose_name_plural': 'Accès documents',
            },
        ),
    ]
