# Generated by Django 6.0.6 on 2026-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerisqueia',
            name='anomalie_detectee',
            field=models.BooleanField(default=False),
        ),
    ]
