# Generated by Django 6.0.6 on 2026-07-13 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_risk', '0002_scorerisqueia_anomalie_detectee'),
        ('signatures', '0007_signature_source_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseSignatureIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_signature', models.CharField(blank=True, choices=[('DRAW', 'Signature dessinée'), ('UPLOAD', 'Signature importée')], max_length=20)),
                ('image_hash', models.CharField(blank=True, max_length=100)),
                ('distance_min', models.FloatField(blank=True, null=True)),
                ('distance_moyenne', models.FloatField(blank=True, null=True)),
                ('niveau_risque', models.CharField(choices=[('REFERENCE', 'Référence'), ('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('SUSPECT', 'Suspect')], default='REFERENCE', max_length=20)),
                ('anomalie_detectee', models.BooleanField(default=False)),
                ('explication', models.TextField(blank=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_ia', to='signatures.signature')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_signature_ia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ScoreRisqueIA',
        ),
    ]
